name: CI Cross Build and Test

on:
  push:
    branches:
      - '**develop**'
      - main
  pull_request:
    branches:
      - '**develop**'
      - main

jobs:
  cross_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Run Build and Test Script
        run: |
          chmod +x ci.sh
          bash ci.sh

      - name: Deploy
        run: echo "Deploy step placeholder"